# -*- coding: utf-8 -*-
#
# Author:        tohhy
# Date:          2011/11/06
# Modifier:      giginet
#

SYNTAXES = {
    'txt' : 'Plain Text', 
    'as' : 'ActionScript', 
    'c' : 'C', 
    'cs' : 'C#', 
    'cpp' : 'C++', 
    'lisp' : 'Common Lisp', 
    'coffee' : 'CoffeeScript',
    'css' : 'CSS', 
    'diff' : 'Diff', 
    'el' : 'Emacs Lisp', 
    'erl' : 'Erlang', 
    'hs' : 'Haskell', 
    'html' : 'HTML', 
    'java' : 'Java', 
    'js' : 'JavaScript', 
    'lua' : 'Lua', 
    'm' : 'Objective-C', 
    'pl' : 'Perl', 
    'aw' : 'PHP', 
    'py' : 'Python', 
    'rb' : 'Ruby', 
    'scala' : 'Scala', 
    'scm' : 'Scheme', 
    'sql' : 'SQL', 
    'tex' : 'TeX', 
    'xml' : 'XML',
    'adb' : 'Ada', 
    'scpt' : 'AppleScript', 
    'arc' : 'Arc', 
    'asp' : 'ASP', 
    'asm' : 'Assembly', 
    'ahk' : 'AutoHotkey', 
    'bat' : 'Batchfile', 
    'befunge' : 'Befunge', 
    'bmx' : 'BlitzMax', 
    'boo' : 'Boo', 
    'b' : 'Brainfuck', 
    'c-objdump' : 'C-ObjDump', 
    'ck' : 'ChucK', 
    'clj' : 'Clojure', 
    'cmake' : 'CMake', 
    'coffee' : 'CoffeeScript', 
    'cfm' : 'ColdFusion', 
    'cppobjdump' : 'Cpp-ObjDump', 
    'feature' : 'Cucumber', 
    'pyx' : 'Cython', 
    'd' : 'D', 
    'd-objdump' : 'D-ObjDump', 
    'darcspatch' : 'Darcs Patch', 
    'pas' : 'Delphi', 
    'dylan' : 'Dylan', 
    'e' : 'Eiffel', 
    'fs' : 'F#', 
    'factor' : 'Factor', 
    'fy' : 'Fancy', 
    'f90' : 'FORTRAN', 
    's' : 'GAS', 
    'kid' : 'Genshi', 
    'ebuild' : 'Gentoo Ebuild', 
    'eclass' : 'Gentoo Eclass', 
    'po' : 'Gettext Catalog', 
    'go' : 'Go', 
    'gs' : 'Gosu', 
    'man' : 'Groff', 
    'groovy' : 'Groovy', 
    'gsp' : 'Groovy Server Pages', 
    'haml' : 'Haml', 
    'hx' : 'HaXe', 
    'mustache' : 'HTML+Django', 
    'erb' : 'HTML+ERB', 
    'phtml' : 'HTML+PHP', 
    'cfg' : 'INI', 
    'io' : 'Io', 
    'ik' : 'Ioke', 
    'weechatlog' : 'IRC log', 
    'jsp' : 'Java Server Pages', 
    'json' : 'JSON', 
    'ly' : 'LilyPond', 
    'lhs' : 'Literate Haskell', 
    'll' : 'LLVM', 
    'mak' : 'Makefile', 
    'mao' : 'Mako', 
    'md' : 'Markdown', 
    'matlab' : 'Matlab', 
    'mxt' : 'Max/MSP', 
    'minid' : 'MiniD', 
    'duby' : 'Mirah', 
    'moo' : 'Moocode', 
    'mu' : 'mupad', 
    'myt' : 'Myghty', 
    'n' : 'Nemerle', 
    'nim' : 'Nimrod', 
    'nu' : 'Nu', 
    'numpy' : 'NumPy', 
    'objdump' : 'ObjDump', 
    'j' : 'Objective-J', 
    'ml' : 'OCaml', 
    'ooc' : 'ooc', 
    'cl' : 'OpenCL', 
    'parrot' : 'Parrot', 
    'pasm' : 'Parrot Assembly', 
    'pir' : 'Parrot Internal Representation', 
    'pl' : 'Prolog', 
    'pd' : 'Pure Data', 
    'pytb' : 'Python traceback', 
    'r' : 'R', 
    'rkt' : 'Racket', 
    'raw' : 'Raw token data', 
    'r' : 'Rebol', 
    'cw' : 'Redcode', 
    'rst' : 'reStructuredText', 
    'rhtml' : 'RHTML', 
    'rs' : 'Rust', 
    'sass' : 'Sass', 
    'scss' : 'SCSS', 
    'self' : 'Self', 
    'sh' : 'Shell', 
    'st' : 'Smalltalk', 
    'tpl' : 'Smarty', 
    'sml' : 'Standard ML', 
    'sc' : 'SuperCollider', 
    'tcl' : 'Tcl', 
    'tcsh' : 'Tcsh', 
    'textile' : 'Textile', 
    'twig' : 'Twig', 
    'vala' : 'Vala', 
    'v' : 'Verilog', 
    'vhd' : 'VHDL', 
    'vim' : 'VimL', 
    'vb' : 'Visual Basic', 
    'xq' : 'XQuery', 
    'xs' : 'XS', 
    'yml' : 'YAML',
}
